


CREATE TABLE TCUSTOMERORDERPAYMENT (
  CUSTOMERORDERPAYMENT_ID NUMBER(19,0) NOT NULL,
  CARD_EXPIRY_MONTH varchar2(2) DEFAULT NULL,
  CARD_EXPIRY_YEAR varchar2(4) DEFAULT NULL,
  CARD_HOLDER_NAME varchar2(128) DEFAULT NULL,
  CARD_NUMBER varchar2(4) DEFAULT NULL,
  CARD_START_DATE datetime DEFAULT NULL,
  CARD_TYPE varchar2(64) DEFAULT NULL,
  CREATED_BY varchar2(64) DEFAULT NULL,
  CREATED_TIMESTAMP datetime DEFAULT NULL,
  GUID varchar2(36) DEFAULT NULL,
  ORDER_CURRENCY varchar2(3) NOT NULL,
  ORDER_DATE datetime NOT NULL,
  ORDER_DELIVERY_AMOUNT decimal(19,2) NOT NULL,
  ORDER_NUMBER varchar2(128) NOT NULL,
  ORDER_SHIPMENT_NUMBER varchar2(128) NOT NULL,
  PP_BATCH_SETTLEMENT bit(1) NOT NULL,
  PP_REZCODE varchar2(128) NOT NULL,
  TRAN_AUTH_CODE varchar2(256) DEFAULT NULL,
  TRAN_PAYMENT_GATEWAY varchar2(128) NOT NULL,
  TRAN_PAYMENT_OP varchar2(128) NOT NULL,
  TRAN_PAYMENT_REZCODE varchar2(128) DEFAULT NULL,
  TRAN_PAYMENT_REZMSG varchar2(1024) DEFAULT NULL,
  TRAN_REFERENCE_ID varchar2(128) DEFAULT NULL,
  TRAN_REQUEST_TOKEN varchar2(256) DEFAULT NULL,
  UPDATED_BY varchar2(64) DEFAULT NULL,
  UPDATED_TIMESTAMP datetime DEFAULT NULL,
  PRIMARY KEY (CUSTOMERORDERPAYMENT_ID)
) ;


CREATE TABLE TPAYMENTGATEWAYPARAMETER (
  PAYMENTGATEWAYPARAMETER_ID NUMBER(19,0) NOT NULL,
  CREATED_BY varchar2(64) DEFAULT NULL,
  CREATED_TIMESTAMP datetime DEFAULT NULL,
  P_DESCRIPTION varchar2(265) DEFAULT NULL,
  GUID varchar2(36) DEFAULT NULL,
  P_LABEL varchar2(64) DEFAULT NULL,
  P_NAME varchar2(64) DEFAULT NULL,
  PG_LABEL varchar2(64) DEFAULT NULL,
  UPDATED_BY varchar2(64) DEFAULT NULL,
  UPDATED_TIMESTAMP datetime DEFAULT NULL,
  P_VALUE varchar2(4000) DEFAULT NULL,
  PRIMARY KEY (PAYMENTGATEWAYPARAMETER_ID)
)  ;
