/*
 * Copyright 2009 Denys Pavlov, Igor Azarnyi
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *        http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */
package org.yes.cart.domain.entity.impl;


import org.yes.cart.domain.entity.Shop;
import org.yes.cart.domain.misc.Pair;
import org.yes.cart.utils.DomainApiUtils;
import org.yes.cart.utils.MoneyUtils;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDateTime;

/**
 * User: Igor Azarny iazarny@yahoo.com
 * Date: 27 0ct 2012
 * Time: 9:10 AM
 */
public class SkuPriceEntity implements org.yes.cart.domain.entity.SkuPrice, java.io.Serializable {

    private long skuPriceId;
    private long version;

    private String skuCode;
    private Shop shop;
    private String currency;
    private BigDecimal quantity;
    private boolean priceUponRequest;
    private boolean priceOnOffer;
    private BigDecimal regularPrice;
    private BigDecimal salePrice;
    private BigDecimal minimalPrice;
    private LocalDateTime salefrom;
    private LocalDateTime saleto;
    private Instant createdTimestamp;
    private Instant updatedTimestamp;
    private String createdBy;
    private String updatedBy;
    private String guid;
    private String tag;
    private String pricingPolicy;
    private String ref;
    private boolean autoGenerated;

    public SkuPriceEntity() {
    }


    @Override
    public String getSkuCode() {
        return skuCode;
    }

    @Override
    public void setSkuCode(final String skuCode) {
        this.skuCode = skuCode;
    }

    @Override
    public Shop getShop() {
        return this.shop;
    }

    @Override
    public void setShop(final Shop shop) {
        this.shop = shop;
    }

    @Override
    public String getCurrency() {
        return this.currency;
    }

    @Override
    public void setCurrency(final String currency) {
        this.currency = currency;
    }

    @Override
    public BigDecimal getQuantity() {
        return this.quantity;
    }

    @Override
    public void setQuantity(final BigDecimal quantity) {
        this.quantity = quantity;
    }

    @Override
    public boolean isPriceUponRequest() {
        return priceUponRequest;
    }

    @Override
    public void setPriceUponRequest(final boolean priceUponRequest) {
        this.priceUponRequest = priceUponRequest;
    }

    @Override
    public boolean isPriceOnOffer() {
        return priceOnOffer;
    }

    @Override
    public void setPriceOnOffer(final boolean priceOnOffer) {
        this.priceOnOffer = priceOnOffer;
    }

    @Override
    public BigDecimal getRegularPrice() {
        return this.regularPrice;
    }

    @Override
    public void setRegularPrice(final BigDecimal regularPrice) {
        this.regularPrice = regularPrice;
    }

    @Override
    public BigDecimal getSalePrice() {
        return this.salePrice;
    }

    /** {@inheritDoc} */
    @Override
    public Pair<BigDecimal, BigDecimal> getSalePriceForCalculation() {
        if (salePrice == null) {
            // No sale price is set only regular should be used
            return new Pair<>(regularPrice, null);
        } else if (MoneyUtils.isFirstBiggerThanOrEqualToSecond(salePrice, regularPrice)) {
            // Overpriced (or sale is the same as regular)
            return new Pair<>(salePrice, null);
        }
        return new Pair<>(regularPrice, salePrice);
    }

    @Override
    public void setSalePrice(final BigDecimal salePrice) {
        this.salePrice = salePrice;
    }

    @Override
    public BigDecimal getMinimalPrice() {
        return this.minimalPrice;
    }

    @Override
    public void setMinimalPrice(final BigDecimal minimalPrice) {
        this.minimalPrice = minimalPrice;
    }

    @Override
    public LocalDateTime getSalefrom() {
        return this.salefrom;
    }

    @Override
    public void setSalefrom(final LocalDateTime salefrom) {
        this.salefrom = salefrom;
    }

    @Override
    public LocalDateTime getSaleto() {
        return this.saleto;
    }

    @Override
    public void setSaleto(final LocalDateTime saleto) {
        this.saleto = saleto;
    }


    @Override
    public boolean isAvailable(final LocalDateTime now) {
        return DomainApiUtils.isObjectAvailableNow(true, this.salefrom, this.saleto, now);
    }

    @Override
    public Instant getCreatedTimestamp() {
        return this.createdTimestamp;
    }

    @Override
    public void setCreatedTimestamp(final Instant createdTimestamp) {
        this.createdTimestamp = createdTimestamp;
    }

    @Override
    public Instant getUpdatedTimestamp() {
        return this.updatedTimestamp;
    }

    @Override
    public void setUpdatedTimestamp(final Instant updatedTimestamp) {
        this.updatedTimestamp = updatedTimestamp;
    }

    @Override
    public String getCreatedBy() {
        return this.createdBy;
    }

    @Override
    public void setCreatedBy(final String createdBy) {
        this.createdBy = createdBy;
    }

    @Override
    public String getUpdatedBy() {
        return this.updatedBy;
    }

    @Override
    public void setUpdatedBy(final String updatedBy) {
        this.updatedBy = updatedBy;
    }

    @Override
    public String getGuid() {
        return this.guid;
    }

    @Override
    public void setGuid(final String guid) {
        this.guid = guid;
    }

    @Override
    public String getTag() {
        return tag;
    }

    @Override
    public void setTag(final String tag) {
        this.tag = tag;
    }

    @Override
    public String getPricingPolicy() {
        return pricingPolicy;
    }

    @Override
    public void setPricingPolicy(final String pricingPolicy) {
        this.pricingPolicy = pricingPolicy;
    }

    @Override
    public String getRef() {
        return ref;
    }

    @Override
    public void setRef(final String ref) {
        this.ref = ref;
    }

    @Override
    public boolean isAutoGenerated() {
        return autoGenerated;
    }

    @Override
    public void setAutoGenerated(final boolean autoGenerated) {
        this.autoGenerated = autoGenerated;
    }

    @Override
    public long getSkuPriceId() {
        return this.skuPriceId;
    }

    @Override
    public long getId() {
        return this.skuPriceId;
    }

    @Override
    public void setSkuPriceId(final long skuPriceId) {
        this.skuPriceId = skuPriceId;
    }

    @Override
    public long getVersion() {
        return version;
    }

    public void setVersion(final long version) {
        this.version = version;
    }
}


