package org.yes.cart.domain.entity;
// Generated 25-Sep-2009 4:08:12 PM by Hibernate Tools 3.2.2.GA


/**
 * ShopDiscountRule generated by hbm2java
 */

public interface ShopDiscountRule extends Auditable {

    /**
     */
    public long getShopDiscountRuleId();

    public void setShopDiscountRuleId(long shopDiscountRuleId);

    /**
     */
    public String getRule();

    public void setRule(String rule);

    /**
     */
    public String getName();

    public void setName(String name);

    /**
     */
    public String getDescription();

    public void setDescription(String description);

}


