--
--  Copyright 2009 Inspire-Software.com
--
--     Licensed under the Apache License, Version 2.0 (the "License");
--     you may not use this file except in compliance with the License.
--     You may obtain a copy of the License at
--
--         http://www.apache.org/licenses/LICENSE-2.0
--
--     Unless required by applicable law or agreed to in writing, software
--     distributed under the License is distributed on an "AS IS" BASIS,
--     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
--     See the License for the specific language governing permissions and
--     limitations under the License.
--

--
-- This script is for MySQL only with some Derby hints inline with comments
-- We highly recommend you seek YC's support help when upgrading your system
-- for detailed analysis of your code.
--
-- Upgrades organised in blocks representing JIRA tasks for which they are
-- necessary - potentially you may hand pick the upgrades you required but
-- to keep upgrade process as easy as possible for future we recommend full
-- upgrades
--

--
-- YC-1042 Show more feature on category lister pages
--

INSERT INTO TATTRIBUTE (ATTRIBUTE_ID, GUID, CODE, MANDATORY, VAL, NAME, DESCRIPTION, ETYPE, ATTRIBUTEGROUP, STORE, SEARCH, SEARCHPRIMARY, NAV)
  VALUES (  11130,  'SHOP_CATEGORY_PAGE_CTRL_DISABLE', 'SHOP_CATEGORY_PAGE_CTRL_DISABLE',  0,  NULL,  'Category: Hide pagination controls on category page',
   'Hide pagination buttons on the category page',  'Boolean', 'SHOP', 0, 0, 0, 0);

INSERT INTO TATTRIBUTE (ATTRIBUTE_ID, GUID, CODE, MANDATORY, VAL, NAME, DESCRIPTION, ETYPE, ATTRIBUTEGROUP, STORE, SEARCH, SEARCHPRIMARY, NAV)
  VALUES (  11131,  'SHOP_CATEGORY_SORT_CTRL_DISABLE', 'SHOP_CATEGORY_SORT_CTRL_DISABLE',  0,  NULL,  'Category: Hide sorting controls on category page',
   'Disable sorting buttons on the category page',  'Boolean', 'SHOP', 0, 0, 0, 0);

INSERT INTO TATTRIBUTE (ATTRIBUTE_ID, GUID, CODE, MANDATORY, VAL, NAME, DESCRIPTION, ETYPE, ATTRIBUTEGROUP, STORE, SEARCH, SEARCHPRIMARY, NAV)
  VALUES (  11132,  'SHOP_CATEGORY_PAGESIZE_CTRL_DISABLE', 'SHOP_CATEGORY_PAGESIZE_CTRL_DISABLE',  0,  NULL,  'Category: Hide page size controls on category page',
   'Disable page size buttons on the category page',  'Boolean', 'SHOP', 0, 0, 0, 0);

INSERT INTO TATTRIBUTE (ATTRIBUTE_ID, GUID, CODE, MANDATORY, VAL, NAME, DESCRIPTION, ETYPE, ATTRIBUTEGROUP, STORE, SEARCH, SEARCHPRIMARY, NAV)
  VALUES (  11133,  'SHOP_CATEGORY_SHOWMORE_CTRL_DISABLE', 'SHOP_CATEGORY_SHOWMORE_CTRL_DISABLE',  0,  NULL,  'Category: Hide show more controls on category page',
   'Disable show more buttons on the category page',  'Boolean', 'SHOP', 0, 0, 0, 0);

--
-- YC-1037 Job schedules abstraction layer
--

    create table TJOBDEFINITION (
        JOBDEFINITION_ID bigint not null auto_increment,
        VERSION bigint not null default 0,
        JOB_NAME varchar(255) not null unique,
        PROCESSOR varchar(255) not null,
        CONTEXT longtext,
        HOST_REGEX varchar(45),
        DEFAULT_CRON varchar(25),
        DEFAULT_CRON_KEY varchar(100),
        DEFAULT_PAUSED  bit not null default 0,
        GUID varchar(100) not null unique,
        CREATED_TIMESTAMP datetime,
        UPDATED_TIMESTAMP datetime,
        CREATED_BY varchar(64),
        UPDATED_BY varchar(64),
        primary key (JOBDEFINITION_ID)
    );

    create table TJOB (
        JOB_ID bigint not null auto_increment,
        VERSION bigint not null default 0,
        NODE_ID varchar(45) not null,
        JOB_DEFINITION_CODE varchar(100) not null,
        CRON varchar(25),
        PAUSED  bit not null default 0,
        DISABLED  bit not null default 0,
        LAST_RUN  datetime,
        LAST_REPORT longtext,
        CHECKPOINT  datetime,
        GUID varchar(36) not null unique,
        CREATED_TIMESTAMP datetime,
        UPDATED_TIMESTAMP datetime,
        CREATED_BY varchar(64),
        UPDATED_BY varchar(64),
        primary key (JOB_ID)
    );

    create index JOBDEFINITION_GUID on TJOBDEFINITION (GUID);
    create index JOB_JD_CODE on TJOB (JOB_DEFINITION_CODE);

--     create table TJOBDEFINITION (
--         JOBDEFINITION_ID bigint not null GENERATED BY DEFAULT AS IDENTITY,
--         VERSION bigint not null default 0,
--         JOB_NAME varchar(255) not null unique,
--         PROCESSOR varchar(255) not null,
--         CONTEXT varchar(4000),
--         HOST_REGEX varchar(45),
--         DEFAULT_CRON varchar(25),
--         DEFAULT_CRON_KEY varchar(100),
--         DEFAULT_PAUSED  smallint not null default 0,
--         GUID varchar(100) not null unique,
--         CREATED_TIMESTAMP timestamp,
--         UPDATED_TIMESTAMP timestamp,
--         CREATED_BY varchar(64),
--         UPDATED_BY varchar(64),
--         primary key (JOBDEFINITION_ID)
--     );
--
--     create table TJOB (
--         JOB_ID bigint not null GENERATED BY DEFAULT AS IDENTITY,
--         VERSION bigint not null default 0,
--         NODE_ID varchar(45) not null,
--         JOB_DEFINITION_CODE varchar(100) not null,
--         CRON varchar(25),
--         PAUSED  smallint not null default 0,
--         DISABLED  smallint not null default 0,
--         LAST_RUN  timestamp,
--         LAST_REPORT varchar(4000),
--         CHECKPOINT  timestamp,
--         GUID varchar(36) not null unique,
--         CREATED_TIMESTAMP timestamp,
--         UPDATED_TIMESTAMP timestamp,
--         CREATED_BY varchar(64),
--         UPDATED_BY varchar(64),
--         primary key (JOB_ID)
--     );
--
--     create index JOBDEFINITION_GUID on TJOBDEFINITION (GUID);
--     create index JOB_JD_CODE on TJOB (JOB_DEFINITION_CODE);

-- manager-cronjob.xml ---------------

-- BulkMailProcessorImpl
INSERT INTO TJOBDEFINITION (JOBDEFINITION_ID, GUID, JOB_NAME, PROCESSOR, CONTEXT, HOST_REGEX, DEFAULT_CRON_KEY, DEFAULT_PAUSED)
  VALUES (1001, 'sendMailJob', 'Send Mail', 'bulkMailProcessor', '', '^(ADM)$', 'admin.cron.sendMailJob', 1);
-- LocalFileShareImportListenerImpl
DELETE FROM TSYSTEMATTRVALUE WHERE CODE IN ('JOB_LOCAL_FILE_IMPORT_PAUSE', 'JOB_LOCAL_FILE_IMPORT_FS_ROOT');
DELETE FROM TATTRIBUTE WHERE CODE IN ('JOB_LOCAL_FILE_IMPORT_PAUSE', 'JOB_LOCAL_FILE_IMPORT_FS_ROOT');
INSERT INTO TJOBDEFINITION (JOBDEFINITION_ID, GUID, JOB_NAME, PROCESSOR, CONTEXT, HOST_REGEX, DEFAULT_CRON_KEY, DEFAULT_PAUSED)
  VALUES (1002, 'autoImportJob', 'Auto Import', 'autoImportListener', 'file-import-root=/set/path/here
# set groups e.g.
SHOP10.config.0.group=YC DEMO: Initial Data
SHOP10.config.0.regex=import\\.zip
SHOP10.config.0.reindex=true
SHOP10.config.0.user=admin@yes-cart.com
SHOP10.config.0.pass=xxxxxx',
    '^(ADM)$', 'admin.cron.autoImportJob', 1);
-- RawDataImporterRunnerImpl
DELETE FROM TSYSTEMATTRVALUE WHERE CODE IN ('JOB_RAW_DATA_IMPORT_PAUSE');
DELETE FROM TATTRIBUTE WHERE CODE IN ('JOB_RAW_DATA_IMPORT_PAUSE');
-- LocalFileShareImageVaultProcessorImpl
DELETE FROM TSYSTEMATTRVALUE WHERE CODE IN ('JOB_LOCAL_IMAGEVAULT_SCAN_PAUSE');
DELETE FROM TATTRIBUTE WHERE CODE IN ('JOB_LOCAL_IMAGEVAULT_SCAN_PAUSE');
INSERT INTO TJOBDEFINITION (JOBDEFINITION_ID, GUID, JOB_NAME, PROCESSOR, CONTEXT, HOST_REGEX, DEFAULT_CRON_KEY, DEFAULT_PAUSED)
  VALUES (1003, 'imageVaultProcessorJob', 'Image Vault Scanner', 'imageVaultProcessor', 'config.user=admin@yes-cart.com
config.pass=xxxxxx
config.reindex=true',
    '^(ADM)$', 'admin.cron.imageVaultProcessorJob', 1);
-- LocalFileShareProductImageVaultCleanupProcessorImpl
DELETE FROM TSYSTEMATTRVALUE WHERE CODE IN ('JOB_LOCAL_PRODIMAGECLEAN_SCAN_PAUSE', 'JOB_LOCAL_PRODIMAGEVAULT_CLEAN_MODE');
DELETE FROM TATTRIBUTE WHERE CODE IN ('JOB_LOCAL_PRODIMAGECLEAN_SCAN_PAUSE', 'JOB_LOCAL_PRODIMAGEVAULT_CLEAN_MODE');
INSERT INTO TJOBDEFINITION (JOBDEFINITION_ID, GUID, JOB_NAME, PROCESSOR, CONTEXT, HOST_REGEX, DEFAULT_CRON_KEY, DEFAULT_PAUSED)
  VALUES (1004, 'productImageVaultCleanupProcessorJob', 'Product Image Vault Clean Up', 'productImageVaultCleanupProcessor', 'clean-mode=scan',
    '^(ADM)$', 'admin.cron.productImageVaultCleanupProcessorJob', 1);
-- CacheEvictionQueueProcessorImpl
DELETE FROM TSYSTEMATTRVALUE WHERE CODE IN ('JOB_CACHE_EVICT_PAUSE');
DELETE FROM TATTRIBUTE WHERE CODE IN ('JOB_CACHE_EVICT_PAUSE');
INSERT INTO TJOBDEFINITION (JOBDEFINITION_ID, GUID, JOB_NAME, PROCESSOR, CONTEXT, HOST_REGEX, DEFAULT_CRON_KEY, DEFAULT_PAUSED)
  VALUES (1005, 'cacheEvictionQueueJob', 'Evict frontend cache', 'cacheEvictionQueueProcessor', null,
    '^(ADM)$', 'admin.cron.cacheEvictionQueueJob', 0);


-- core-manager-cronjob.xml ---------------

-- BulkCustomerTagProcessorImpl
DELETE FROM TSYSTEMATTRVALUE WHERE CODE IN ('JOB_CUSTOMER_TAG_BATCH_SIZE', 'JOB_CUSTOMER_TAG_PAUSE');
DELETE FROM TATTRIBUTE WHERE CODE IN ('JOB_CUSTOMER_TAG_BATCH_SIZE', 'JOB_CUSTOMER_TAG_PAUSE');
INSERT INTO TJOBDEFINITION (JOBDEFINITION_ID, GUID, JOB_NAME, PROCESSOR, CONTEXT, HOST_REGEX, DEFAULT_CRON_KEY, DEFAULT_PAUSED)
  VALUES (1101, 'customerTagJob', 'Customer Tagging', 'bulkCustomerTagProcessor', 'process-batch-size=500',
    '^(ADM)$', 'admin.cron.customerTagJob', 1);
-- BulkAbandonedShoppingCartProcessorImpl
DELETE FROM TSYSTEMATTRVALUE WHERE CODE IN ('JOB_ABANDONED_CARTS_BATCH_SIZE', 'CART_ABANDONED_TIMEOUT_SECONDS', 'JOB_ABANDONED_CARTS_PAUSE');
DELETE FROM TATTRIBUTE WHERE CODE IN ('JOB_ABANDONED_CARTS_BATCH_SIZE', 'CART_ABANDONED_TIMEOUT_SECONDS', 'JOB_ABANDONED_CARTS_PAUSE');
INSERT INTO TJOBDEFINITION (JOBDEFINITION_ID, GUID, JOB_NAME, PROCESSOR, CONTEXT, HOST_REGEX, DEFAULT_CRON_KEY, DEFAULT_PAUSED)
  VALUES (1102, 'abandonedShoppingCartJob', 'Abandoned Shopping Cart State Clean Up', 'bulkAbandonedShoppingCartProcessor', 'process-batch-size=500
abandoned-timeout-seconds=2592000',
    '^(ADM)$', 'admin.cron.abandonedShoppingCartJob', 0);
-- BulkEmptyAnonymousShoppingCartProcessorImpl
DELETE FROM TSYSTEMATTRVALUE WHERE CODE IN ('JOB_EMPTY_CARTS_BATCH_SIZE', 'CART_EMPTY_ANONYMOUS_TIMEOUT_SECONDS', 'JOB_EMPTY_CARTS_PAUSE');
DELETE FROM TATTRIBUTE WHERE CODE IN ('JOB_EMPTY_CARTS_BATCH_SIZE', 'CART_EMPTY_ANONYMOUS_TIMEOUT_SECONDS', 'JOB_EMPTY_CARTS_PAUSE');
INSERT INTO TJOBDEFINITION (JOBDEFINITION_ID, GUID, JOB_NAME, PROCESSOR, CONTEXT, HOST_REGEX, DEFAULT_CRON_KEY, DEFAULT_PAUSED)
  VALUES (1103, 'emptyAnonymousShoppingCartJob', 'Empty Anonymous Shopping Cart State Clean Up', 'bulkEmptyAnonymousShoppingCartProcessor', 'process-batch-size=500
empty-timeout-seconds=86400',
    '^(ADM)$', 'admin.cron.emptyAnonymousShoppingCartJob', 0);
-- BulkExpiredGuestsProcessorImpl
DELETE FROM TSYSTEMATTRVALUE WHERE CODE IN ('JOB_EXPIRE_GUESTS_BATCH_SIZE', 'GUESTS_EXPIRY_TIMEOUT_SECONDS', 'JOB_EXPIRE_GUESTS_PAUSE');
DELETE FROM TATTRIBUTE WHERE CODE IN ('JOB_EXPIRE_GUESTS_BATCH_SIZE', 'GUESTS_EXPIRY_TIMEOUT_SECONDS', 'JOB_EXPIRE_GUESTS_PAUSE');
INSERT INTO TJOBDEFINITION (JOBDEFINITION_ID, GUID, JOB_NAME, PROCESSOR, CONTEXT, HOST_REGEX, DEFAULT_CRON_KEY, DEFAULT_PAUSED)
  VALUES (1104, 'expiredGuestsJob', 'Expired Guest Accounts Clean Up', 'bulkExpiredGuestsProcessor', 'process-batch-size=500
guest-timeout-seconds=86400',
    '^(ADM)$', 'admin.cron.expiredGuestsJob', 0);
-- RemoveObsoleteProductProcessorImpl
DELETE FROM TSYSTEMATTRVALUE WHERE CODE IN ('JOB_PROD_OBS_BATCH_SIZE', 'JOB_PROD_OBS_MAX', 'JOB_PROD_OBS_PAUSE');
DELETE FROM TATTRIBUTE WHERE CODE IN ('JOB_PROD_OBS_BATCH_SIZE', 'JOB_PROD_OBS_MAX', 'JOB_PROD_OBS_PAUSE');
INSERT INTO TJOBDEFINITION (JOBDEFINITION_ID, GUID, JOB_NAME, PROCESSOR, CONTEXT, HOST_REGEX, DEFAULT_CRON_KEY, DEFAULT_PAUSED)
  VALUES (1105, 'removeObsoleteProductProcessorJob', 'Remove obsolete products', 'removeObsoleteProductProcessor', 'process-batch-size=500
obsolete-timeout-days=365',
    '^(ADM)$', 'admin.cron.removeObsoleteProductProcessorJob', 1);

-- core-index-cronjob.xml ---------------------------

-- ProductsGlobalIndexProcessorImpl
DELETE FROM TSYSTEMATTRVALUE WHERE CODE IN ('JOB_REINDEX_PRODUCT_BATCH_SIZE', 'JOB_GLOBALREINDEX_PAUSE');
DELETE FROM TATTRIBUTE WHERE CODE IN ('JOB_REINDEX_PRODUCT_BATCH_SIZE', 'JOB_GLOBALREINDEX_PAUSE');
INSERT INTO TJOBDEFINITION (JOBDEFINITION_ID, GUID, JOB_NAME, PROCESSOR, CONTEXT, HOST_REGEX, DEFAULT_CRON_KEY, DEFAULT_PAUSED)
  VALUES (1201, 'productsGlobalIndexProcessorJob', 'Reindex All Products', 'productsGlobalIndexProcessor', 'reindex-batch-size=100',
    '^((API)|(SF[A-Z]))$', 'ws.cron.productsGlobalIndexProcessorJob', 1);
-- ProductInventoryChangedProcessorImpl
DELETE FROM TSYSTEMATTRVALUE WHERE CODE LIKE 'JOB_PRODINVUP_LR_%';
DELETE FROM TATTRIBUTE  WHERE CODE LIKE 'JOB_PRODINVUP_LR_%';
DELETE FROM TSYSTEMATTRVALUE WHERE CODE IN ('JOB_REINDEX_PRODUCT_BATCH_SIZE', 'JOB_PRODINVUP_DELTA', 'JOB_PRODINVUP_FULL', 'JOB_PRODINVUP_DELTA_S', 'JOB_PRODINVUP_PAUSE');
DELETE FROM TATTRIBUTE  WHERE CODE IN ('JOB_REINDEX_PRODUCT_BATCH_SIZE', 'JOB_PRODINVUP_DELTA', 'JOB_PRODINVUP_FULL', 'JOB_PRODINVUP_DELTA_S', 'JOB_PRODINVUP_PAUSE');
INSERT INTO TJOBDEFINITION (JOBDEFINITION_ID, GUID, JOB_NAME, PROCESSOR, CONTEXT, HOST_REGEX, DEFAULT_CRON_KEY, DEFAULT_PAUSED)
  VALUES (1202, 'productInventoryChangedProcessorJob', 'Inventory Changes Product Indexing', 'productInventoryChangedProcessor', 'reindex-batch-size=100
inventory-full-threshold=1000
inventory-delta-seconds=15
inventory-update-delta=100',
    '^((API)|(SF[A-Z]))$', 'ws.cron.productInventoryChangedProcessorJob', 0);


-- core-export-cronjob.xml ---------------------------

-- OrderAutoExportProcessorImpl
DELETE FROM TSYSTEMATTRVALUE WHERE CODE IN ('JOB_ORDER_AUTO_EXPORT_PAUSE');
DELETE FROM TATTRIBUTE WHERE CODE IN ('JOB_ORDER_AUTO_EXPORT_PAUSE');
INSERT INTO TJOBDEFINITION (JOBDEFINITION_ID, GUID, JOB_NAME, PROCESSOR, CONTEXT, HOST_REGEX, DEFAULT_CRON_KEY, DEFAULT_PAUSED)
  VALUES (1301, 'orderAutoExportProcessorJob', 'Order Auto Export Processing', 'orderAutoExportProcessor', '',
    '^(ADM)$', 'admin.cron.orderAutoExportProcessorJob', 1);


-- core-orderstate-cronjob.xml ---------------------------

-- BulkAwaitingInventoryDeliveriesProcessorImpl
DELETE FROM TSYSTEMATTRVALUE WHERE CODE IN ('JOB_DELIVERY_WAIT_INVENTORY_PAUSE', 'JOB_DELWAITINV_LR');
DELETE FROM TATTRIBUTE WHERE CODE IN ('JOB_DELIVERY_WAIT_INVENTORY_PAUSE', 'JOB_DELWAITINV_LR');
INSERT INTO TJOBDEFINITION (JOBDEFINITION_ID, GUID, JOB_NAME, PROCESSOR, CONTEXT, HOST_REGEX, DEFAULT_CRON_KEY, DEFAULT_PAUSED)
  VALUES (1401, 'preorderJob', 'Inventory Awaiting Delivery Processing', 'bulkAwaitingInventoryDeliveriesProcessor', '',
    '^(ADM)$', 'admin.cron.preorderJob', 0);
-- OrderDeliveryInfoUpdateProcessorImpl
DELETE FROM TSYSTEMATTRVALUE WHERE CODE IN ('JOB_DELIVERY_INFO_UPDATE_PAUSE');
DELETE FROM TATTRIBUTE WHERE CODE IN ('JOB_DELIVERY_INFO_UPDATE_PAUSE');
INSERT INTO TJOBDEFINITION (JOBDEFINITION_ID, GUID, JOB_NAME, PROCESSOR, CONTEXT, HOST_REGEX, DEFAULT_CRON_KEY, DEFAULT_PAUSED)
  VALUES (1402, 'deliveryInfoUpdateJob', 'Order Delivery Information Update Processing', 'orderDeliveryInfoUpdateProcessor', '',
    '^(ADM)$', 'admin.cron.deliveryInfoUpdateJob', 0);


-- core-pricerules-cronjob.xml --------------

-- BulkPriceRuleProcessorImpl
DELETE FROM TSYSTEMATTRVALUE WHERE CODE IN ('JOB_PRICE_RULES_BATCH_SIZE', 'JOB_PRICE_RULES_PAUSE');
DELETE FROM TATTRIBUTE WHERE CODE IN ('JOB_PRICE_RULES_BATCH_SIZE', 'JOB_PRICE_RULES_PAUSE');
INSERT INTO TJOBDEFINITION (JOBDEFINITION_ID, GUID, JOB_NAME, PROCESSOR, CONTEXT, HOST_REGEX, DEFAULT_CRON_KEY, DEFAULT_PAUSED)
  VALUES (1501, 'priceGeneratorJob', 'Price generator', 'bulkPriceRuleProcessor', 'process-batch-size=500',
  '^(ADM)$', 'admin.cron.priceGeneratorJob', 1);

-- int-module-pim-icecat.xml --------------
-- DailyIndexProcessorV2Impl
DELETE FROM TSYSTEMATTRVALUE WHERE CODE IN ('JOB_ICE_DAILY_PAUSE');
DELETE FROM TATTRIBUTE WHERE CODE IN ('JOB_ICE_DAILY_PAUSE');
INSERT INTO TJOBDEFINITION (JOBDEFINITION_ID, GUID, JOB_NAME, PROCESSOR, CONTEXT, HOST_REGEX, DEFAULT_CRON_KEY, DEFAULT_PAUSED)
  VALUES (1601, 'iceCatDailyIndexJobV2', 'IceCat Daily Index Update (V2)', 'iceCatDailyIndexProcessorV2', null,
  '^(ADM)$', 'admin.cron.iceCatDailyIndexJobV2', 1);
-- BrandAttributesProcessorImpl
DELETE FROM TSYSTEMATTRVALUE WHERE CODE IN ('JOB_ICE_ENHANCE_B_PAUSE');
DELETE FROM TATTRIBUTE WHERE CODE IN ('JOB_ICE_ENHANCE_B_PAUSE');
INSERT INTO TJOBDEFINITION (JOBDEFINITION_ID, GUID, JOB_NAME, PROCESSOR, CONTEXT, HOST_REGEX, DEFAULT_CRON_KEY, DEFAULT_PAUSED)
  VALUES (1602, 'iceCatBrandAttributesJob', 'IceCat Brand Attributes Enhancer', 'iceCatBrandAttributesProcessor', null,
  '^(ADM)$', 'admin.cron.iceCatBrandAttributesJob', 1);
-- AuthenticatedProductAttributesProcessorImpl
DELETE FROM TSYSTEMATTRVALUE WHERE CODE IN ('JOB_ICE_ENHANCE_PAUSE');
DELETE FROM TATTRIBUTE WHERE CODE IN ('JOB_ICE_ENHANCE_PAUSE');
INSERT INTO TJOBDEFINITION (JOBDEFINITION_ID, GUID, JOB_NAME, PROCESSOR, CONTEXT, HOST_REGEX, DEFAULT_CRON_KEY, DEFAULT_PAUSED)
  VALUES (1603, 'iceCatProductAttributesJob', 'IceCat Product Attributes Enhancer', 'authenticatedIceCatProductAttributesProcessor', null,
  '^(ADM)$', 'admin.cron.iceCatProductAttributesJob', 1);

